syms COM_theta COM_theta_dot wheel_theta_dot real

% simplify(77*COM_theta_dot^2*cos(COM_theta)^3 - 1962*cos(conj(COM_theta))*cos(COM_theta) + 1962*sin(conj(COM_theta))*sin(COM_theta) - 20*COM_theta_dot*wheel_theta_dot*cos(COM_theta)^2 + 20*COM_theta_dot*wheel_theta_dot*sin(COM_theta)^2 + 77*COM_theta_dot^2*cos(COM_theta)*sin(COM_theta)^2 + 20*cos(conj(COM_theta))*conj(COM_theta_dot)*cos(COM_theta)*conj(wheel_theta_dot) - 20*sin(conj(COM_theta))*conj(COM_theta_dot)*sin(COM_theta)*conj(wheel_theta_dot))/(20*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)) - (cos(COM_theta)*sin(COM_theta)*(77*COM_theta_dot^2*sin(COM_theta)^3 - 1962*sin(conj(COM_theta))*cos(COM_theta) + 200*tau*cos(COM_theta)^2 + 200*tau*sin(COM_theta)^2 + 77*COM_theta_dot^2*cos(COM_theta)^2*sin(COM_theta) - 20*COM_theta_dot*wheel_theta_dot*cos(COM_theta)*sin(COM_theta) + 20*sin(conj(COM_theta))*conj(COM_theta_dot)*cos(COM_theta)*conj(wheel_theta_dot)))/(10*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)^2)
% simplify(-(20*COM_theta_dot*cos(COM_theta)*sin(COM_theta) - 20*sin(conj(COM_theta))*conj(COM_theta_dot)*cos(COM_theta))/(20*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)))
% simplify(154*COM_theta_dot*sin(COM_theta)^3 - 20*wheel_theta_dot*cos(COM_theta)*sin(COM_theta) + 154*COM_theta_dot*cos(COM_theta)^2*sin(COM_theta) + 20*sin(conj(COM_theta))*cos(COM_theta)*conj(wheel_theta_dot))/(20*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2))
% simplify(7848*cos(conj(COM_theta)) - 77*COM_theta_dot^2*cos(COM_theta)^2 + 77*COM_theta_dot^2*sin(COM_theta)^2 + 200*tau*sin(COM_theta) + 80*COM_theta_dot*wheel_theta_dot*cos(COM_theta) - 80*cos(conj(COM_theta))*conj(COM_theta_dot)*conj(wheel_theta_dot))/(77*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)) + (2*cos(COM_theta)*sin(COM_theta)*(200*tau*cos(COM_theta) - 7848*sin(conj(COM_theta)) + 77*COM_theta_dot^2*cos(COM_theta)*sin(COM_theta) - 80*COM_theta_dot*wheel_theta_dot*sin(COM_theta) + 80*sin(conj(COM_theta))*conj(COM_theta_dot)*conj(wheel_theta_dot)))/(77*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)^2)
% simplify(-(80*sin(conj(COM_theta))*conj(COM_theta_dot) - 80*COM_theta_dot*sin(COM_theta))/(77*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)))
% simplify(-(80*sin(conj(COM_theta))*conj(wheel_theta_dot) - 80*wheel_theta_dot*sin(COM_theta) + 154*COM_theta_dot*cos(COM_theta)*sin(COM_theta))/(77*(3*cos(COM_theta)^2 + 4*sin(COM_theta)^2)))



simplify((77*COM_theta_dot^2*cos(COM_theta)^3 - 13734*cos(COM_theta)^2 + 154*COM_theta_dot^2*cos(COM_theta) - 200*tau*sin(2*COM_theta) + 7848)/(20*(cos(COM_theta)^2 - 4)^2))
simplify((15696*cos(COM_theta) + 7848*cos(COM_theta)^3 - 539*COM_theta_dot^2*cos(COM_theta)^2 + 800*tau*sin(COM_theta) + 308*COM_theta_dot^2 + 200*tau*cos(COM_theta)^2*sin(COM_theta))/(77*(cos(COM_theta)^2 - 4)^2))