% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Apr-2026 17:36:14
%  MATLAB version: 25.1.0.2973910 (R2025a) Update 1
% -------------------------------------------------------------------
                                          

Param = Simulink.Parameter;
Param.Value = [];
Param.Complexity = 'real';
Param.CoderInfo.StorageClass = 'Auto';
Param.Description = '';
Param.DataType = 'auto';
Param.Min = [];
Param.Max = [];
Param.DocUnits = '';

color = struct;
color.orange = [1 0.6 0];
color.red = [1 0.2 0];
color.dgreen = [0 0.4 0];
color.green = [0 0.6 0];
color.lgreen = [0 0.8 0];
color.dblue = [0 0.2 1];
color.blue = [0.2 0.6 1];
color.lblue = [0.4 0.8 1];
color.brown = [0.4 0.2 0];
color.lbrown = [0.8 0.4 0];
color.yellow = [1 0.8 0];
color.lyellow = [1 1 0];
color.black = [0 0 0];
color.white = [1 1 1];
color.dgrey = [0.3 0.3 0.3];
color.grey = [0.5 0.5 0.5];
color.lgrey = [0.7 0.7 0.7];
color.vlgrey = [0.9 0.9 0.9];

density = struct;
density.wood = 650;
density.plastic = 920;
density.water = 1000;
density.aluminum = 2700;
density.steel = 7800;
density.titanium = 4500;
density.brass = 8600;

robot = struct;
robot.base = struct;
robot.base.height = 100;
robot.base.radius = 12;
robot.torso = struct;
robot.torso.height = 90;
robot.torso.radius = 9;
robot.head = struct;
robot.head.length = 30;
robot.head.width = 24;
robot.head.height = 20;
robot.lowerarmpin = struct;
robot.lowerarmpin.radius = 1;
robot.lowerarmpin.height = 3;
robot.shoulder = struct;
robot.shoulder.offset = 15;
robot.upperarm = struct;
robot.upperarm.length = 70;
robot.upperarm.iradius = 8;
robot.upperarm.oradius = 6;
robot.upperarm.thickness = 6;
robot.middlearm = struct;
robot.middlearm.length = 30;
robot.middlearm.radius = 6;
robot.middlearm.width = 10;
robot.middlearm.thickness = 5;
robot.lowerarm = struct;
robot.lowerarm.length = 50;
robot.lowerarm.radius = 3;
robot.lowerarm.width = 10;
robot.lowerarm.thickness = 5;
robot.ujoint = struct;
robot.ujoint.plate = struct;
robot.ujoint.plate.length = 55;
robot.ujoint.plate.width = 40;
robot.ujoint.plate.thickness = 10;
robot.ujoint.axle = struct;
robot.ujoint.axle.offset = 30;
robot.ujoint.axle.radius = 10;
robot.ujoint.crosspiece = struct;
robot.ujoint.crosspiece.length = 64;
robot.ujoint.crosspiece.radius = 10;
robot.gripper = struct;
robot.gripper.basethickness = 10;
robot.gripper.baseradius = 18;
robot.gripper.tipradius = 10;
robot.gripper.clawlength = 50;
robot.gripper.tipdepth = 15;
robot.gripper.channelradius = 5;
robot.tool = struct;
robot.tool.length = 15;
robot.tool.shaftradius = 0.5;
robot.tool.tiplength = 1.5;
robot.tool.tiporadius = 0.3;
robot.tool.tipiradius = 1.2;
robot.tool.location = [93; -15; 193];
robot.wrist = struct;
robot.wrist.offset = 6;
robot.workpiece = struct;
robot.workpiece.location = [120; 0; 150];
robot.workpiece.rotation = ...
  [0 0 -1;
   -1 0 0;
   0 1 0];

workpiece = struct;
workpiece.distance = 120;
workpiece.height = 150;
workpiece.glyphsep = 40;
workpiece.plate = struct;
workpiece.plate.length = 140;
workpiece.plate.width = 50;
workpiece.plate.thickness = 2;
workpiece.beadsize = 0.5;
workpiece.plus = struct;
workpiece.plus.armlength = 20;
workpiece.circle = struct;
workpiece.circle.radius = 10;
workpiece.star = struct;
workpiece.star.radius = 10;
workpiece.tool = struct;
workpiece.tool.home = [15; 43; 27];
workpiece.tool.zoffset = 6;

%% New variables
robot.width = 0.2;

floor = struct;
floor.length = robot.width * 2;
floor.width = 5;
floor.thickness = 0.1;

motion_tc = 0.02;

wheel = struct;
wheel.radius = 0.2 / 2;
wheel.thickness = 0.01;

lowerLeg = struct;
lowerLeg.length = 0.3;
lowerLeg.width = 0.02;
lowerLeg.thickness = 0.005;

upperLeg = struct;
upperLeg.length = 0.3;
upperLeg.width = 0.02;
upperLeg.thickness = 0.005;

joint_offset = lowerLeg.length * 0.05;
